### ISSUE TITLE
master fails to cross-compile with mingw toolchain

### ISSUE THREAD

**Issue by hillu** [plusvic/yara#253]
Trying to build with

    ./configure --host=i686-w64-mingw32 && make

on my Debian system currently fails. (it worked with 3.2.0):

    In file included from rules.c:27:0:
    ./include/yara/filemap.h:23:28: error: conflicting types for 'int64_t'
     #define off_t              int64_t
                                ^
    In file included from /usr/lib/gcc/i686-w64-mingw32/4.9-win32/include/stdint.h:9
    :0,
                     from ./include/yara/arena.h:20,
                     from ./include/yara/re.h:22,
                     from ./include/yara/atoms.h:21,
                     from ./include/yara/ahocorasick.h:21,
                     from rules.c:22:
    /usr/share/mingw-w64/include/stdint.h:41:38: note: previous declaration of 'int64_t' was here
     __MINGW_EXTENSION typedef long long  int64_t;
                                          ^
    rules.c:63:12: error: conflicting types for 'yr_rules_define_integer_variable'
     YR_API int yr_rules_define_integer_variable(
                ^
    In file included from ./include/yara/exec.h:23:0,
                     from rules.c:25:
    ./include/yara/rules.h:100:12: note: previous declaration of 'yr_rules_define_integer_variable' was here
     YR_API int yr_rules_define_integer_variable(
                ^
    Makefile:607: recipe for target 'rules.lo' failed

**Comment by plusvic** [comment]
off_t can be 32-bits wide in some systems, so yr_filemap_map_ex should use off_t. 

From the error report I don't completely understand why the compiler complains about a redeclaration of int64_t. I'm trying to reproduce the issue but I'm finding other issues with mingw, neither "log" or "log2" seems to be defined in math.h.

**Comment by hillu** [comment]
* Victor M. Alvarez:

> off_t can be 32-bits wide in some systems, so yr_filemap_map_ex should use off_t.

And yet you define it as a 64 bit type on Windows (commit
a546391e939cb6c6d6d351585c0de8d3d4f0b8d9) which goes against MinGW's
definition (at least for Win32)...

Did you introduce that #define because the Microsoft compiler doesn't
know about off_t?

Cheers,
-Hilko

**Comment by plusvic** [comment]
Yes, off_t was defined as int64_t because Microsoft compiler doesn't know about off_t. So the problem was that in mingw both off_t and _WIN32 are defined. Your new patch fixed the problem.

By the way, did you experienced any problem with "log" function?

**Comment by hillu** [comment]
* Victor M. Alvarez:

> Yes, off_t was defined as int64_t because Microsoft compiler doesn't know about off_t. So the problem was that in mingw
> both off_t and _WIN32 are defined. Your new patch fixed the problem.
>
> By the way, did you experienced any problem with "log" function?

No. For the record, I am using
mingw-w64-{common,i686-dev,x86-64-dev,tools} 3.2.0-2 and
gcc-mingw-w64-{i686,x86-64} 4.9.2-10+15 from Debian/unstable.

Cheers,
-Hilko
